name = "t"
type = "cart_checkout_validation"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/t.wasm"

[ui.paths]
create = "/"
details = "/"
