# This file stores configurations for your Shopify app.

scopes = "write_products, write_discounts, read_delivery_customizations, write_delivery_customizations, read_payment_customizations, write_payment_customizations"
